version: '3.3'
services:
  formbuilder:
    image: histacoohri/ngx-openmrs-ohri-formbuilder:0.6.2
    x-bake:
      platforms:
        - linux/amd64
        - linux/arm64
    ports:
      - '4200:80'
    environment:
      - OPENMRS_HOST_URL=https://172.17.0.1
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:4200']
      timeout: 5s
